# ***Student Name: Tushar Panchal***

# ***En. No. : 21162101014***

# ***Branch: CBA***

# ***Batch:  71***

# ***Subject: ML (Machine Learning)***

# **EXPERIMENT 8**
###**For  Multiclass classification on Drug prediction dataset, Binary classification on Credit card fraud detection dataset design :**

1. Use following models: logistic regression, knn, decision tree and ANN
2. Calculate Precision, recall, accuracy etc.

###**Regression: Metro Interstate Traffic Volume Dataset :**
1. User multi linear regression, polynomial regression and ANN
2. Calculate MSE, R2 score etc.


####**Drug Prediction Data**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ML_7/p6_drug200.csv")
print("\nData Preview : \n")
print(data.head(10))


Data Preview : 

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  drugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  drugY
9   43   M     LOW      NORMAL   19.368  drugY


In [ ]:
print("\nDataset Information:\n")
data.info()

label_encoder = LabelEncoder()
for col in ['Sex', 'BP', 'Cholesterol', 'Drug']:
    data[col] = label_encoder.fit_transform(data[col])

# Define features (X) and target (y)
X = data.drop('Drug', axis=1)
y = data['Drug']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("\nData preprocessing completed.")
print(f"Training set size: {X_train.shape}, Testing set size: {X_test.shape}")



Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

Data preprocessing completed.
Training set size: (140, 5), Testing set size: (60, 5)


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Feature scaling applied for improved model convergence.")

Feature scaling applied for improved model convergence.


In [ ]:
from imblearn.over_sampling import SMOTE

# Use SMOTE to oversample the minority classes
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_scaled, y_train)

print("Applied SMOTE to balance the dataset.")

Applied SMOTE to balance the dataset.


In [ ]:
models = {
    '📊 Logistic Regression': LogisticRegression(solver='saga', max_iter=3000, random_state=42),
    '🧑‍🤝‍🧑 K-Nearest Neighbors': KNeighborsClassifier(),
    '🌳 Decision Tree': DecisionTreeClassifier(),
    '🧠 Artificial Neural Network': MLPClassifier(hidden_layer_sizes=(10,), max_iter=2000, random_state=42, early_stopping=True, learning_rate_init=0.001)
}

metrics = {}

# Train and evaluate models
for model_name, model in models.items():
    model.fit(X_train_balanced, y_train_balanced)  # Use balanced dataset
    y_pred = model.predict(X_test_scaled)

    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=1)  # Handle undefined metrics
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    # Store metrics in dict
    metrics[model_name] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': cm
    }

print("Training completed!")


Training completed!


In [ ]:
from tabulate import tabulate

#Results
print("\nModel Performance Metrics:\n")
for model_name, metric in metrics.items():
    print(f"\n{model_name} : \n")
    print(f"Confusion Matrix : \n{metric['confusion_matrix']}\n")
    print("-" * 80)

comparison_table = [
    [model,
     f"{metrics[model]['accuracy']:.4f}",
     f"{metrics[model]['precision']:.4f}",
     f"{metrics[model]['recall']:.4f}",
     f"{metrics[model]['f1_score']:.4f}"]
    for model in metrics
]

print("\nComparison of Models : \n")
print(tabulate(
    comparison_table,
    headers=["Model", "Accuracy", "Precision", "Recall", "F1 Score"],
    tablefmt="fancy_grid"
))


Model Performance Metrics:


📊 Logistic Regression : 

Confusion Matrix : 
[[ 7  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  1]
 [ 0  0  0 18  0]
 [ 1  2  0  1 22]]

--------------------------------------------------------------------------------

🧑‍🤝‍🧑 K-Nearest Neighbors : 

Confusion Matrix : 
[[ 7  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  6  0  0]
 [ 0  1  0 17  0]
 [ 2  3  2  3 16]]

--------------------------------------------------------------------------------

🌳 Decision Tree : 

Confusion Matrix : 
[[ 7  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 26]]

--------------------------------------------------------------------------------

🧠 Artificial Neural Network : 

Confusion Matrix : 
[[ 3  0  3  0  1]
 [ 0  0  1  0  2]
 [ 0  0  5  0  1]
 [ 0  0 12  3  3]
 [ 0 14  1  5  6]]

--------------------------------------------------------------------------------

Comparison of Models : 

╒══════════════════════════════╤════════════╤═════════════╤══

####**Credit Card Fraud Detection Data**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df_fraud = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_7/p5_creditcard.csv')
print("\nData Preview : \n", df_fraud.head(10))
print("\nDataset Info : \n")
df_fraud.info()



Data Preview : 
    ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   
5   6    50000.0    1          1         2   37      0      0      0      0   
6   7   500000.0    1          1         2   29      0      0      0      0   
7   8   100000.0    2          2         2   23      0     -1     -1      0   
8   9   140000.0    2          3         1   28      0      0      2      0   
9  10    20000.0    1          3         2   35     -2     -2     -2     -2   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0

In [ ]:
# Preprocessing
X_fraud = df_fraud.drop('default.payment.next.month', axis=1)
y_fraud = df_fraud['default.payment.next.month']

# Scaling
scaler = StandardScaler()
X_fraud_scaled = scaler.fit_transform(X_fraud)

# Splitting
X_train_fraud, X_test_fraud, y_train_fraud, y_test_fraud = train_test_split(
    X_fraud_scaled, y_fraud, test_size=0.3, random_state=42
)
print(f"Training Data Shape: {X_train_fraud.shape}, Test Data Shape: {X_test_fraud.shape}")


Training Data Shape: (21000, 24), Test Data Shape: (9000, 24)


In [ ]:
# Train and Evaluate Models
models_fraud = {
    '📊 Logistic Regression': LogisticRegression(max_iter=2000),
    '🧑‍🤝‍🧑 K-Nearest Neighbors': KNeighborsClassifier(),
    '🌳 Decision Tree': DecisionTreeClassifier(),
}

metrics_fraud = {}

for model_name, model in models_fraud.items():
    model.fit(X_train_fraud, y_train_fraud)
    y_pred_fraud = model.predict(X_test_fraud)

    accuracy = accuracy_score(y_test_fraud, y_pred_fraud)
    precision = precision_score(y_test_fraud, y_pred_fraud, zero_division=0)
    recall = recall_score(y_test_fraud, y_pred_fraud, zero_division=0)
    f1 = f1_score(y_test_fraud, y_pred_fraud, zero_division=0)
    cm = confusion_matrix(y_test_fraud, y_pred_fraud)

    metrics_fraud[model_name] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': cm
    }

print("\nPerformance Metrics for Logistic Regression, KNN, and Decision Tree:")
for model_name, metric in metrics_fraud.items():
    print(f"\nModel : {model_name}\n")
    print(f"  Accuracy: {metric['accuracy']:.4f}")
    print(f"  Precision: {metric['precision']:.4f}")
    print(f"  Recall: {metric['recall']:.4f}")
    print(f"  F1 Score: {metric['f1_score']:.4f}")
    print(f"  \nConfusion Matrix:\n{metric['confusion_matrix']}\n")
    print("-" * 80)



Performance Metrics for Logistic Regression, KNN, and Decision Tree:

Model : 📊 Logistic Regression

  Accuracy: 0.8088
  Precision: 0.6781
  Recall: 0.2321
  F1 Score: 0.3459
  
Confusion Matrix:
[[6824  216]
 [1505  455]]

--------------------------------------------------------------------------------

Model : 🧑‍🤝‍🧑 K-Nearest Neighbors

  Accuracy: 0.7923
  Precision: 0.5378
  Recall: 0.3301
  F1 Score: 0.4091
  
Confusion Matrix:
[[6484  556]
 [1313  647]]

--------------------------------------------------------------------------------

Model : 🌳 Decision Tree

  Accuracy: 0.7273
  Precision: 0.3818
  Recall: 0.4071
  F1 Score: 0.3941
  
Confusion Matrix:
[[5748 1292]
 [1162  798]]

--------------------------------------------------------------------------------


In [ ]:
# ANN Model
ann_model = Sequential([
    Dense(64, input_dim=X_train_fraud.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

ann_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

ann_model.fit(X_train_fraud, y_train_fraud, epochs=50, batch_size=32, verbose=1)

# ANN Predictions
y_pred_fraud_ann = (ann_model.predict(X_test_fraud) > 0.5).astype("int32")

accuracy_ann = accuracy_score(y_test_fraud, y_pred_fraud_ann)
precision_ann = precision_score(y_test_fraud, y_pred_fraud_ann, zero_division=0)
recall_ann = recall_score(y_test_fraud, y_pred_fraud_ann, zero_division=0)
f1_ann = f1_score(y_test_fraud, y_pred_fraud_ann, zero_division=0)
cm_ann = confusion_matrix(y_test_fraud, y_pred_fraud_ann)

metrics_fraud['🤖 Artificial Neural Network (Keras)'] = {
    'accuracy': accuracy_ann,
    'precision': precision_ann,
    'recall': recall_ann,
    'f1_score': f1_ann,
    'confusion_matrix': cm_ann
}

Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7919 - loss: 0.5000
Epoch 2/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8190 - loss: 0.4382
Epoch 3/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8232 - loss: 0.4317
Epoch 4/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8247 - loss: 0.4248
Epoch 5/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8241 - loss: 0.4246
Epoch 6/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8253 - loss: 0.4217
Epoch 7/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8251 - loss: 0.4207
Epoch 8/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8273 - loss: 0.4159
Epoch 9/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8248 - loss: 0.4178
Epoch 10/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8244 - loss: 0.4120
Epoch 11/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8317 - loss: 0.4058
Epoch 12/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy

In [ ]:
from tabulate import tabulate

# Summary of all models
summary_data = []

for model_name, metric in metrics_fraud.items():
    summary_data.append([
        model_name,
        metric['accuracy'],
        metric['precision'],
        metric['recall'],
        metric['f1_score']
    ])

headers = ["Model", "Accuracy", "Precision", "Recall", "F1 Score"]

print("\nFinal Performance Metrics (Tabular Form):")
print(tabulate(summary_data, headers=headers, tablefmt="fancy_grid", floatfmt=".4f"))


Final Performance Metrics (Tabular Form):
╒══════════════════════════════════════╤════════════╤═════════════╤══════════╤════════════╕
│ Model                                │   Accuracy │   Precision │   Recall │   F1 Score │
╞══════════════════════════════════════╪════════════╪═════════════╪══════════╪════════════╡
│ 📊 Logistic Regression               │     0.8088 │      0.6781 │   0.2321 │     0.3459 │
├──────────────────────────────────────┼────────────┼─────────────┼──────────┼────────────┤
│ 🧑‍🤝‍🧑 K-Nearest Neighbors               │     0.7923 │      0.5378 │   0.3301 │     0.4091 │
├──────────────────────────────────────┼────────────┼─────────────┼──────────┼────────────┤
│ 🌳 Decision Tree                     │     0.7273 │      0.3818 │   0.4071 │     0.3941 │
├──────────────────────────────────────┼────────────┼─────────────┼──────────┼────────────┤
│ 🤖 Artificial Neural Network (Keras) │     0.8076 │      0.5995 │   0.3505 │     0.4424 │
╘════════════════════════════════════

####**Metro Interstate Traffic Volume Data**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tabulate import tabulate

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_7/p3_metro.csv')
print("\nData Preview : \n\n", data.head(10))
print()
print("-" * 100)
print("\nDataset Info : \n")
data.info()
print()

data.drop(['holiday', 'weather_main', 'weather_description', 'date_time'], axis=1, inplace=True)

data.fillna(data.mean(), inplace=True)

print("-" * 100)

print("\nProcessed Data : \n\n", data.head(10))

X = data.drop('traffic_volume', axis=1)
y = data['traffic_volume']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


Data Preview : 

   holiday    temp  rain_1h  snow_1h  clouds_all weather_main  \
0     NaN  288.28      0.0      0.0          40       Clouds   
1     NaN  289.36      0.0      0.0          75       Clouds   
2     NaN  289.58      0.0      0.0          90       Clouds   
3     NaN  290.13      0.0      0.0          90       Clouds   
4     NaN  291.14      0.0      0.0          75       Clouds   
5     NaN  291.72      0.0      0.0           1        Clear   
6     NaN  293.17      0.0      0.0           1        Clear   
7     NaN  293.86      0.0      0.0           1        Clear   
8     NaN  294.14      0.0      0.0          20       Clouds   
9     NaN  293.10      0.0      0.0          20       Clouds   

  weather_description            date_time  traffic_volume  
0    scattered clouds  2012-10-02 09:00:00            5545  
1       broken clouds  2012-10-02 10:00:00            4516  
2     overcast clouds  2012-10-02 11:00:00            4767  
3     overcast clouds  2012-10-0

In [ ]:
# Multi-linear regression

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

y_pred_linear = linear_model.predict(X_test)

mse_linear = mean_squared_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)

In [ ]:
# Transform features to polynomial degree 2
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Polynomial Regression
poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

y_pred_poly = poly_model.predict(X_test_poly)

mse_poly = mean_squared_error(y_test, y_pred_poly)
r2_poly = r2_score(y_test, y_pred_poly)

In [ ]:
# ANN

ann_model = Sequential()
ann_model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
ann_model.add(Dense(32, activation='relu'))
ann_model.add(Dense(1, activation='linear'))

ann_model.compile(optimizer='adam', loss='mse', metrics=['mse'])

ann_model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

y_pred_ann = ann_model.predict(X_test).flatten()

mse_ann = mean_squared_error(y_test, y_pred_ann)
r2_ann = r2_score(y_test, y_pred_ann)

Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1055/1055 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7313807.0000 - mse: 7313807.0000
Epoch 2/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3870035.0000 - mse: 3870035.0000
Epoch 3/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 3885662.0000 - mse: 3885662.0000
Epoch 4/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 3866673.2500 - mse: 3866673.2500
Epoch 5/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 3866383.0000 - mse: 3866383.0000
Epoch 6/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 3855736.0000 - mse: 3855736.0000
Epoch 7/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3850028.2500 - mse: 3850028.2500
Epoch 8/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 3855265.0000 - mse: 3855265.0000
Epoch 9/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 3834307.7500 - mse: 3834307.7500
Epoch 10/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 3850098.7500 - mse: 3850098.7500
Epoch 11/50
1055/1055 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - los

In [ ]:
# Results

results = [
    ['🔥 Multi-Linear Regression', mse_linear, r2_linear],
    ['⭐ Polynomial Regression (Degree 2)', mse_poly, r2_poly],
    ['🤖 Artificial Neural Network', mse_ann, r2_ann]
]

print("\nComparison of Models : \n")
print(tabulate(results, headers=['Model', 'MSE', 'R² Score'], tablefmt='fancy_grid'))


Comparison of Models : 

╒═════════════════════════════════════╤═════════════╤════════════╕
│ Model                               │         MSE │   R² Score │
╞═════════════════════════════════════╪═════════════╪════════════╡
│ 🔥 Multi-Linear Regression          │ 3.87516e+06 │  0.025468  │
├─────────────────────────────────────┼─────────────┼────────────┤
│ ⭐ Polynomial Regression (Degree 2) │ 3.83033e+06 │  0.0367421 │
├─────────────────────────────────────┼─────────────┼────────────┤
│ 🤖 Artificial Neural Network        │ 3.83208e+06 │  0.0363016 │
╘═════════════════════════════════════╧═════════════╧════════════╛
